SELECT REGION_NAME ,COUNTRY_NAME,CITY,STREET_ADDRESS
    FROM HR.REGIONS R,HR.COUNTRIES C,HR.LOCATIONS L
    WHERE R.REGION_ID = C.REGION_ID AND L.COUNTRY_ID = C.COUNTRY_ID
    
    
select XMLELEMENT("HR",
        XMLAGG(
            XMLELEMENT("DIRECCIONES_REGIONES",XMLATTRIBUTES(L.LOCATION_ID AS id),
                XMLFOREST(
                    R.REGION_NAME AS "REGION",
                    C.COUNTRY_NAME AS "PAIS",
                    L.CITY AS "CIUDAD",
                    L.STREET_ADDRESS AS "DIRECCION")
            )
        ) AS AGG
    )AS HR
FROM HR.REGIONS R,HR.COUNTRIES C,HR.LOCATIONS L
WHERE R.REGION_ID = C.REGION_ID AND L.COUNTRY_ID = C.COUNTRY_ID